export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_FAILED = "LOGIN_REQUEST_FAILED";

export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const AUTO_LOGIN_REQUEST = "AUTO_LOGIN_REQUEST";
// export const AUTO_LOGIN_SUCCESS = "AUTO_LOGIN_SUCCESS";
// export const AUTO_LOGIN_FAILED = "AUTO_LOGIN_FAILED";

export const ADD_FILE = "ADD_FILE";
export const UPLOAD_FILE_REQUEST = "UPLOAD_FILE_REQUEST";
export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS";
export const UPLOAD_FILE_FAILED = "UPLOAD_FILE_FAILED";